# fly.toml app configuration file generated for reactivities-sample-app on 2024-02-06T13:06:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-sample-app'
primary_region = 'waw'

[build]
  image = 'dciepiela00/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dxe84cnj6"
  Cloudinary__ApiKey="646872157566138"
  Facebook_AppId = "1104205840781277"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
